# Generated by Django 4.2.7 on 2024-11-22 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("position", models.IntegerField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["level", "position"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=50,
                    ),
                ),
                ("points_to_advance", models.IntegerField(default=0)),
                ("position", models.IntegerField(unique=True)),
                ("passing_score", models.IntegerField(default=80)),
                ("unlocked_by_test", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LevelTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passing_score", models.IntegerField(default=80)),
                ("total_questions", models.IntegerField()),
                (
                    "generated_from_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_tests",
                        to="lessons.level",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="lessons.level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("passing_score", models.IntegerField(default=80)),
                ("total_questions", models.IntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lessons.level",
            ),
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("definition", models.TextField()),
                ("example", models.TextField()),
                ("translation", models.CharField(blank=True, max_length=100)),
                (
                    "fill_in_blank_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Template with _____ for fill-in-blank exercises",
                    ),
                ),
                ("position", models.IntegerField()),
                ("is_last_card", models.BooleanField(default=False)),
                (
                    "blank_placeholder",
                    models.CharField(
                        default="_____",
                        help_text="Placeholder for fill-in-blank answers",
                        max_length=50,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "position"],
                "unique_together": {("lesson", "position")},
            },
        ),
        migrations.CreateModel(
            name="UserQuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0)),
                ("is_passed", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "quiz")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_flashcards", models.IntegerField(default=0)),
                ("quiz_score", models.FloatField(default=0)),
                ("quiz_completed", models.BooleanField(default=False)),
                ("level_test_score", models.FloatField(default=0)),
                ("level_unlocked", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("time_spent", models.IntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.lesson"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.level"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson", "level")},
            },
        ),
        migrations.CreateModel(
            name="UserFlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "flashcard")},
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=200)),
                ("position", models.IntegerField()),
                (
                    "fill_in_blank_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Template with _____ for fill-in-blank exercises",
                    ),
                ),
                (
                    "blank_placeholder",
                    models.CharField(
                        default="_____",
                        help_text="Placeholder for fill-in-blank answers",
                        max_length=50,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lessons.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["quiz", "position"],
                "unique_together": {("quiz", "position")},
            },
        ),
        migrations.CreateModel(
            name="LevelTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=200)),
                ("position", models.IntegerField()),
                (
                    "fill_in_blank_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Template with _____ for fill-in-blank exercises",
                    ),
                ),
                (
                    "blank_placeholder",
                    models.CharField(
                        default="_____",
                        help_text="Placeholder for fill-in-blank answers",
                        max_length=50,
                    ),
                ),
                (
                    "level_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lessons.leveltest",
                    ),
                ),
            ],
            options={
                "ordering": ["level_test", "position"],
                "unique_together": {("level_test", "position")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("level", "position")},
        ),
    ]
