# Generated by Django 4.2.7 on 2024-11-21 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="level_position",
        ),
    ]
