# Generated by Django 5.1.2 on 2024-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.TextField(default='What is the meaning of this word?'),
        ),
    ]
