services:
  redis:
    image: redis:6-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"] 
    env_file:
      - .env.prod.local
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.prod.local
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 3

networks:
  default:
    name: e-learn-network
