services:
  - type: web
    name: it-learn-backend
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /healthcheck
    numInstances: 1
    buildCommand: docker build -t it-learn-app .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 2 --worker-class=gthread --worker-tmp-dir /dev/shm --max-requests 1000 --max-requests-jitter 50 --timeout 120 run:create_app()
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "false"
      - key: MONGODB_URI
        value: "mongodb+srv://badrribzat:wzFoMfXhaESdzqog@e-learn.1jzxy.mongodb.net/e-learn?retryWrites=true&w=majority&authSource=admin&ssl=true&tlsAllowInvalidCertificates=true"
      - key: MONGO_USER
        value: "badrribzat"
      - key: MONGO_PASSWORD
        value: "wzFoMfXhaESdzqog"
      - key: REDIS_HOST
        fromService:
          type: redis
          name: it-learn-redis
          property: host
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: ML_MODEL_PATH
        value: "en_core_web_sm"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    resources:
      cpu: 0.25
      memory: 512M
      storage: 512M

  - type: redis
    name: it-learn-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru
    maxmemory: 256mb
