services:
  - type: web
    name: it-learn-backend
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /healthcheck
    numInstances: 1
    buildCommand: docker build -t it-learn-app .
    startCommand: gunicorn --bind 0.0.0.0:${PORT} --workers 2 --threads 2 --worker-class=gthread --worker-tmp-dir /dev/shm --max-requests 1000 --max-requests-jitter 50 --timeout 120 --log-level info --access-logfile - --error-logfile - 'run:create_app()'
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "false"
      - key: MONGODB_URI
        sync: false
        value: ${MONGODB_URI}
      - key: MONGO_USER
        sync: false
        value: ${MONGO_USER}
      - key: MONGO_PASSWORD
        sync: false
        value: ${MONGO_PASSWORD}
      - key: REDIS_HOST
        fromService:
          type: redis
          name: it-learn-redis
          property: host
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: ML_MODEL_PATH
        value: "en_core_web_sm"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    resources:
      cpu: 0.25
      memory: 512M
      storage: 512M
    healthcheck:
      httpGet:
        path: /healthcheck
        port: ${PORT}
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    logging:
      json: true
      level: info
      destination: papertrail

  - type: redis
    name: it-learn-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru
    maxmemory: 256mb
    args: ["--requirepass", "${REDIS_PASSWORD}"]

# Rate Limiting (matching K8s ingress configuration)
services:
  - type: web
    name: it-learn-backend
    rateLimit:
      requests: 1000
      period: 1m

# Additional configurations
services:
  - type: web
    name: it-learn-backend
    docker:
      dockerfile: Dockerfile
      context: .
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
