apiVersion: v1
kind: Secret
metadata:
  name: e-learn-secrets
  namespace: e-learn
type: Opaque
data:
  SECRET_KEY: MjNxV1FZWUtPT2Y4YjlfVVRRLU5CcTRWUGhiRTNuMzBScG04eS1XRERIX2NFVWptbXVCeFFhWkp4NWFmc3F2dA==
  REDIS_PASSWORD: WXJ4SDd5YTZBY2t0enFSeW1xd0lCbzNtMDNaNmtjYzFXSXQ0R00wWDlFMD0=
  MONGO_USER: YmFkcnJpYnphdA==
  MONGO_PASSWORD: d3pGb01mWGhhRVNkenFvZw==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9iYWRycmliemF0Ond6Rm9NZlhoYUVTZHpxb2dAZS1sZWFybi4xanp4eS5tb25nb2RiLm5ldC9lLWxlYXJuP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhdXRoU291cmNlPWFkbWluJnNzbD10cnVlJnRsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVl
